dataset_dir: benchmark/syrup-datasets
# exclude_datasets:
  # - rsv-a_aligned-nuc_2023-01-01
results_dir: benchmark/results
logs_dir: benchmark/logs
metrics_dir: benchmark/metrics

replicates: 3
threads: 1
branch_support: true
branch_support_method: sprta
branch_support_replicates: 1000
filter_divergent_samples: false
max_divergence_percent: 6.7

browser:
  host: 127.0.0.1
  start_port: 5173
  server_timeout_seconds: 120

cmaple:
  build_dir: benchmark/build/cmaple-cli
  binary: benchmark/build/cmaple-cli/cmaple
