[workspace]
authors = ["Wytamma Wirth <wytamma.wirth@me.com>"]
channels = ["conda-forge", "bioconda"]
name = "syrup"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
install-binaryen = "bash scripts/install-binaryen-wasm.sh"
build-libomp = "bash scripts/build-libomp-wasm.sh"
build-wasm = "bash scripts/install-binaryen-wasm.sh && bash scripts/build-cmaple-threaded.sh"

[dependencies]
emscripten = ">=4.0.9,<5"
cmake = ">=4.3.2,<5"
make = ">=4.4.1,<5"
