[workspace]
authors = ["LeoFeatherstone <leofeatherstone@protonmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "syrup_sims"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
tskit = ">=1.0.3,<2"
msprime = ">=1.4.2,<2"
